version: '3'

services:
  cyberchef:
    container_name: draw.io
    image: jgraph/drawio:latest
    networks:
      - traefik_default
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.drawio.entrypoints: "websecure"
      traefik.http.routers.drawio.rule: "Host(`drawio.signaturegraph.net`)"
      traefik.http.routers.drawio.tls: "true"
      traefik.http.routers.drawio.tls.certresolver: "staging"
networks:
  traefik_default:
    external: true