version: '3'

services:
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:arm64v8-latest
    environment:
      TZ: 'America/Chicago'
      PUID: '1000'
      PGID: '1000'
    volumes:
      - /mnt/service-data/heimdall:/config
    restart: unless-stopped
    networks:
      - name: traefik-test_default
    labels:
      traefik.enable: "true"
      traefik.http.routers.heimdall.entrypoints: "websecure"
      traefik.http.routers.heimdall.rule: "Host(`heimdall.signaturegraph.net`)"
      traefik.http.routers.heimdall.tls: "true"
      traefik.http.routers.heimdall.tls.certresolver: "staging"