version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
      - "8082:443/tcp"
    environment:
      TZ: 'America/Chicago'
      DNS1: 1.1.1.1
      DNS2: 9.9.9.9
    volumes:
      - /mnt/service-data/pihole/etcd:/etc/pihole
      - /mnt/service-data/pihole/dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped