version: '3'

services:
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_default
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.cyberchef.entrypoints: "websecure"
      traefik.http.routers.cyberchef.rule: "Host(`cyberchef.signaturegraph.net`)"
      traefik.http.routers.cyberchef.tls: "true"
      traefik.http.routers.cyberchef.tls.certresolver: "staging"
networks:
  traefik_default:
    external: true